# CircleCI Version
version: 2.1

# Executors
executors:
  default:
    docker:
      - image: circleci/node:8.11

# Orbs
orbs:
  aws-s3: circleci/aws-s3@1.0.9

# Jobs
jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build React App
          command: REACT_APP_ENV=production npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy-prod:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install python pip
          command: sudo apt-get install python-pip python-dev -y
      - aws-s3/sync:
          from: ./build
          to: "s3://cimple-web-common/"

# Workflows
workflows:
  build_deploy:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build
