# CircleCI Version
version: 2.1

# Executors
executors:
  default:
    docker:
      - image: circleci/node:8.11

# Orbs
orbs:
  aws-s3: circleci/aws-s3@1.0.9

# Jobs
jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build React App
          command: REACT_APP_ENV=production npm run build && npm run build-storybook
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - dist
            - storybook-static

  release:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Semantic release
          command: npx semantic-release
      - run:
          name: Install python pip
          command: sudo apt-get install python-pip python-dev -y
      - aws-s3/sync:
          from: ./storybook-static
          to: "s3://cimple-web-common/"
          overwrite: true

# Workflows
workflows:
  all:
    jobs:
      - build
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - build
