version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install python pip
          command: sudo apt-get install python-pip python-dev -y

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Configure awscli
          command: aws configure set preview.cloudfront true

      - run:
          name: Install npm dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Make credentials
          command: ./.make_credentials.sh

      - run:
          name: Build and Deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              REACT_APP_ENV=production REACT_APP_FB=${REACT_APP_FB} REACT_APP_MAPBOX=${REACT_APP_MAPBOX} npm run build && aws s3 sync ./build s3://lixomarinho.app/ --delete --region us-east-1 --profile production && aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*' --profile production
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              REACT_APP_ENV=staging REACT_APP_FB=${REACT_APP_FB} REACT_APP_MAPBOX=${REACT_APP_MAPBOX} npm run build && aws s3 sync ./build s3://staging.lixomarinho.app/ --delete --region us-east-1 --profile staging && aws cloudfront create-invalidation --distribution-id ${STAGING_CLOUDFRONT_DISTRIBUTION_ID} --paths '/*' --profile staging
            else
              echo "Not master branch so not deploying"
            fi
