import Arrow from './Arrow';
import Next from './Next';
import Prev from './Prev';
import Cart from './Cart';
import CartEmpty from './CartEmpty';
import CaretUp from './CaretUp';
import CaretDown from './CaretDown';
import CaretRight from './CaretRight';
import Close from './Close';
import Danger from './Danger';
import DoubleChevron from './DoubleChevron';
import External from './External';
import Search from './Search';
import Hamburger from './Hamburger';
import Plus from './Plus';
import PlusBig from './PlusBig';
import Minus from './Minus';
import Edit from './Edit';
import Ellipsis from './Ellipsis';
import ThumbsUp from './ThumbsUp';
import ThumbsDown from './ThumbsDown';
import Verified from './Verified';

const Icons = {};

Icons.Arrow = Arrow;
Icons.Cart = Cart;
Icons.CartEmpty = CartEmpty;
Icons.CaretUp = CaretUp;
Icons.CaretDown = CaretDown;
Icons.CaretRight = CaretRight;
Icons.Close = Close;
Icons.Danger = Danger;
Icons.DoubleChevron = DoubleChevron;
Icons.External = External;
Icons.Search = Search;
Icons.Hamburger = Hamburger;
Icons.Next = Next;
Icons.Prev = Prev;
Icons.Plus = Plus;
Icons.PlusBig = PlusBig;
Icons.Minus = Minus;
Icons.Edit = Edit;
Icons.Ellipsis = Ellipsis;
Icons.ThumbsUp = ThumbsUp;
Icons.ThumbsDown = ThumbsDown;
Icons.Verified = Verified;

export default Icons;
